## Experiments with $\alpha$-values 

This file explores how the $\alpha$-parameter (in the initial guess) affects computation speed.

We fix `grid_max=1e6` based on the numerical experiments in `ex_grid_max.ipynb`.

For each specification, the statistics are calculated by averaging $N$ repeated experiments.

#### Parallel Computing

The code has been parallelized, so it runs very fast, and the time taken is relatively less sensitive to the grid size of asset/saving. 

In [1]:
run optimality

In [6]:
tol = 1e-5                    # tolerance level to terminate time iteration
grid_max, grid_med = 1e6, 10  # maximum and median grid points for saving
α_space = np.array([0, 0.001, 0.01, 0.1, 0.2, 0.5, 1])

#### Case 1. $G = 50$

In [7]:
grid_sizes = 50*np.ones(100).astype('int')  # number of grid points for asset/saving, int64[:]

step_conv_lg, time_elap_lg = speed_conv(α_space, grid_sizes,
                                        grid_max, grid_med,
                                        tol=tol, verbose=False)
mean_step = step_conv_lg.mean(axis=1)
mean_time = time_elap_lg.mean(axis=1)

In [8]:
mean_step

array([ 958., 1278., 1630., 1707., 1712., 1715., 1716.])

In [9]:
mean_time

array([0.42181567, 0.53547473, 0.7172873 , 0.65731947, 0.70936376,
       0.7669671 , 0.70174293])

#### Case 2. $G = 100$

In [11]:
grid_sizes = 100*np.ones(100).astype('int')  # number of grid points for asset/saving, int64[:]

step_conv_mg, time_elap_mg = speed_conv(α_space, grid_sizes,
                                        grid_max, grid_med,
                                        tol=tol, verbose=False)
mean_step = step_conv_mg.mean(axis=1)
mean_time = time_elap_mg.mean(axis=1) 

In [12]:
mean_step

array([1100., 1276., 1628., 1705., 1710., 1713., 1714.])

In [13]:
mean_time

array([0.41505906, 0.47941026, 0.61484263, 0.64757539, 0.64411688,
       0.65225787, 0.6387037 ])

#### Case 3. $G = 1000$

In [14]:
grid_sizes = 1000*np.ones(100).astype('int')  # number of grid points for asset/saving, int64[:]

step_conv_hg, time_elap_hg = speed_conv(α_space, grid_sizes,
                                        grid_max, grid_med,
                                        tol=tol, verbose=False)
mean_step = step_conv_hg.mean(axis=1)
mean_time = time_elap_hg.mean(axis=1) 

In [15]:
mean_step

array([1286., 1275., 1627., 1703., 1708., 1711., 1712.])

In [16]:
mean_time

array([2.18006404, 2.19210033, 2.74057086, 2.89985461, 3.00445076,
       2.99493212, 2.96157764])

In [19]:
# np.savez('simulated data/ex_alpha_table.dat', 
#         step_conv_lg=step_conv_lg, time_elap_lg=time_elap_lg,
#         step_conv_mg=step_conv_mg, time_elap_mg=time_elap_mg,
#         step_conv_hg=step_conv_hg, time_elap_hg=time_elap_hg)

In [21]:
# dat = np.load('simulated data/ex_alpha_table_50avg.dat.npz')

In [ ]:
# dat = np.load('simulated data/ex_alpha_table.dat.npz')

In [4]:
# dat['step_conv'].mean(axis=1)
# dat['time_elap'].mean(axis=1)